In [1]:
import csv
import numpy as np
from sklearn.svm import SVR
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('PricesApple.csv')

In [4]:
df.shape

(1260, 6)

In [6]:
df.head

<bound method NDFrame.head of             date     close       volume      open      high       low
0     2018/04/27  162.3200   35617230.0  164.0000  164.3300  160.6300
1     2018/04/26  164.2200   27850370.0  164.1200  165.7300  163.3700
2     2018/04/25  163.6500   28331540.0  162.6200  165.4200  162.4100
3     2018/04/24  162.9400   33674960.0  165.6700  166.3300  161.2201
4     2018/04/23  165.2400   36396590.0  166.8350  166.9200  164.0900
5     2018/04/20  165.7200   65270950.0  170.5950  171.2184  165.4300
6     2018/04/19  172.8000   34693280.0  174.9500  175.3900  172.6600
7     2018/04/18  177.8400   20544600.0  177.8100  178.8200  176.8800
8     2018/04/17  178.2400   26575010.0  176.4900  178.9365  176.4100
9     2018/04/16  175.8200   21561320.0  175.0301  176.1900  174.8301
10    2018/04/13  174.7300   25100510.0  174.7800  175.8400  173.8500
11    2018/04/12  174.1400   22858840.0  173.4100  175.0000  173.0400
12    2018/04/11  172.4400   22401040.0  172.2300  173.9232  171.7000
13    2018/04/10  173.2500   28567110.0  173.0000  174.0000  171.5300
14    2018/04/09  170.0500   28976200.0  169.8800  173.0900  169.8450
15    2018/04/06  168.3800   34949690.0  170.9700  172.4800  168.2000
16    2018/04/05  172.8000   26750260.0  172.5800  174.2304  172.0800
17    2018/04/04  171.6100   34581850.0  164.8800  172.0100  164.7700
18    2018/04/03  168.3900   30237640.0  167.6400  168.7455  164.8800
19    2018/04/02  166.6800   37425640.0  167.8800  168.9400  164.4700
20    2018/03/29  167.7800   38116290.0  167.8050  171.7500  166.9000
21    2018/03/28  166.4800   41464880.0  167.2500  170.0200  165.1900
22    2018/03/27  168.3400   39824200.0  173.6800  175.1500  166.9200
23    2018/03/26  172.7700   36778560.0  168.0700  173.1000  166.4400
24    2018/03/23  164.9400   40984540.0  168.3900  169.9200  164.9400
25    2018/03/22  168.8500   41335980.0  170.0000  172.6800  168.6000
26    2018/03/21  171.2700   36387880.0  175.0400  175.0900  171.2600
27    2018/03/20  175.2400   19620520.0  175.2400  176.8000  174.9400
28    2018/03/19  175.3000   32931110.0  177.3200  177.4700  173.6600
29    2018/03/16  178.0200   38313330.0  178.6500  179.1200  177.6200
...          ...       ...          ...       ...       ...       ...
1230  2013/06/10   62.6986  112489474.0   63.5328   64.1541   62.4000
1231  2013/06/07   63.1158  101081990.0   62.3571   63.3200   61.8243
1232  2013/06/06   62.6371  104167451.0   63.6386   63.8571   62.0071
1233  2013/06/05   63.5871   72524432.0   63.6643   64.3886   63.3871
1234  2013/06/04   64.1871   72575322.0   64.7457   64.9186   63.9128
1235  2013/06/03   64.3886   92900598.0   64.3900   64.6228   63.2114
1236  2013/05/31   64.2478   95688069.0   64.6428   65.3000   64.2143
1237  2013/05/30   64.5114   88354937.0   63.6643   64.9286   63.5014
1238  2013/05/29   63.5643   82553265.0   62.8571   63.9286   62.7714
1239  2013/05/28   63.0627   96311559.0   64.2714   64.4443   62.9786
1240  2013/05/24   63.5928   69009031.0   62.9786   63.6657   62.9086
1241  2013/05/23   63.1628   88239856.0   62.2786   63.7371   62.2557
1242  2013/05/22   63.0506  110682773.0   63.4357   64.0500   62.6028
1243  2013/05/21   62.8086  113917824.0   62.5928   63.6400   62.0286
1244  2013/05/20   63.2757  112529584.0   61.7014   63.6857   61.4428
1245  2013/05/17   61.8943  106966262.0   62.7214   62.8700   61.5728
1246  2013/05/16   62.0826  150737695.0   60.4628   62.5500   59.8428
1247  2013/05/15   61.2643  185168956.0   62.7371   63.0000   60.3371
1248  2013/05/14   63.4086  111617413.0   64.8357   65.0286   63.1643
1249  2013/05/13   64.9628   79216224.0   64.5014   65.4143   64.5000
1250  2013/05/10   64.7100   83615305.0   65.4243   65.6728   64.3543
1251  2013/05/09   65.2528   99448260.0   65.6871   66.1428   65.0828
1252  2013/05/08   66.2628  117977895.0   65.5771   66.4814   65.1157
1253  2013/05/07   65.5226  120467656.0   66.4243   66.5357   64.8143
1254  2013/05/06   65.8157  123979417.0   65.1014   66.0286   64.9014
1255  2013/05/03   64.2828   90287637.0   64.4728   64.7471   64.1643
1256  2013/05/02   63.6457  105409532.0   63.1114   64.0843   62.9471
1257  2013/05/01   62.7557  126694438.0   63.4943   63.5614   62.0557
1258  2013/04/30   63.2543  172699362.0   62.1571   63.6071   61.7243
1259  2013/04/29   61.4457  159929048.0   60.0643   61.9453   60.0000

[1260 rows x 6 columns]>